name          'bashtoni-findec2'
version       '1.0.0'
source        'UNKNOWN'
author        'Sam Bashton'
license       'Apache License, Version 2.0'
summary       'Generate files based on machines found via EC2 tags'
description   'A small Puppet module to use the https://github.com/BashtonLtd/find-ec2/ utility.'
project_page  'https://github.com/BashtonLtd/puppet-findec2'
